[workspace]
miner_home = "."
node_home = "."

[profile]
account = "A81DDC52F270033F0993E435090AC040"
auth_key = "90333decc01d73fd1a4f57a92cde1c66a81ddc52f270033f0993e435090ac040"
ip = "1.1.1.1"
statement = "Protests rage across the nation"

[chain_info]
chain_id = "0L testnet"
block_dir = "test_fixtures_miner_0"
