[package]
name = "diem-resource-viewer"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem resource viewer"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
diem-workspace-hack = { path = "../../crates/diem-workspace-hack" }
move-resource-viewer = { git = "https://github.com/0LNetworkCommunity/move-0L", rev = "512b8026fb6baa1322d284c70a9d36405d35a6c9" }
diem-types = { path = "../../types"  }
move-core-types = { git = "https://github.com/0LNetworkCommunity/move-0L", rev = "512b8026fb6baa1322d284c70a9d36405d35a6c9" }
move-binary-format = { git = "https://github.com/0LNetworkCommunity/move-0L", rev = "512b8026fb6baa1322d284c70a9d36405d35a6c9" }

anyhow = "1.0.52"
