[admission_control]
address = "0.0.0.0:8000"
need_to_check_mempool_before_validation = false
max_concurrent_inbound_syncs = 100

[admission_control.upstream_proxy_timeout]
secs = 1
nanos = 0

[rpc]
address = "0.0.0.0:8080"

[base]
data_dir = "/opt/libra/data/commmons"
role = "validator"

[base.waypoint]
type = "none"

[consensus]
max_block_size = 1000
contiguous_rounds = 2
max_pruned_blocks_in_mem = 10000
round_initial_timeout_ms = 1000

[consensus.proposer_type]
type = "leader_reputation"
active_weights = 99
inactive_weights = 1
[consensus.safety_rules.backend]
type = "on_disk_storage"
path = "/Users/lucas/code/rust/ol/my_configs/key_store.json"
namespace = "lucas"

[consensus.safety_rules.service]
type = "thread"

[debug_interface]
admission_control_node_debug_port = 6191
metrics_server_port = 9101
public_metrics_server_port = 9102
address = "0.0.0.0"

[execution]
genesis_file_location = ""

[execution.service]
type = "thread"

[[full_node_networks]]
listen_address = "/ip4/0.0.0.0/tcp/6179"
advertised_address = "/ip4/104.131.20.59/tcp/6179"
discovery_interval_ms = 1000
connectivity_check_interval_ms = 5000
enable_remote_authentication = true
discovery_method = "onchain"
network_peers_file = ""
seed_peers_file = "00000000000000000000000000000000.seed_peers.toml"

[full_node_networks.identity]
type = "from_storage"
key_name = "fullnode_network"
peer_id_name = "operator_account"

[full_node_networks.identity.backend]
type = "on_disk_storage"
path = "/Users/lucas/code/rust/ol/my_configs/key_store.json"
namespace = "lucas"

[full_node_networks.network_id]
type = "Private"
name = "VFN"

[logger]
is_async = true
chan_size = 256
level = "INFO"

[metrics]
collection_interval_ms = 1000
dir = "metrics"
enabled = false

[mempool]
broadcast_transactions = true
shared_mempool_tick_interval_ms = 50
shared_mempool_batch_size = 100
shared_mempool_max_concurrent_inbound_syncs = 100
max_broadcasts_per_peer = 25
capacity = 1000000
capacity_per_user = 100
system_transaction_timeout_secs = 86400
system_transaction_gc_interval_ms = 180000

[state_sync]
chunk_limit = 250
tick_interval_ms = 100
long_poll_timeout_ms = 30000
max_chunk_limit = 1000
max_timeout_ms = 120000
sync_request_timeout_ms = 60000

[storage]
address = "127.0.0.1:6666"
backup_service_port = 7777
dir = "libradb/db"
grpc_max_receive_len = 100000000

[upstream]
primary_networks = []
upstream_peers = []
fallback_networks = []

[validator_network]
listen_address = "/ip4/0.0.0.0/tcp/6180"
advertised_address = "/ip4/104.131.20.59/tcp/6180"
discovery_interval_ms = 1000
connectivity_check_interval_ms = 5000
enable_remote_authentication = true
discovery_method = "onchain"
network_peers_file = ""
seed_peers_file = "00000000000000000000000000000000.seed_peers.toml"

[validator_network.identity]
type = "from_storage"
key_name = "validator_network"
peer_id_name = "operator_account"

[validator_network.identity.backend]
type = "on_disk_storage"
path = "/Users/lucas/code/rust/ol/my_configs/key_store.json"
namespace = "lucas"

[validator_network.network_id]
type = "Validator"

[configs_ol_miner]
preimage = ""
proof = ""
