[package]
name = "server"
version = "0.1.0"
authors = ["lpgeiger <1364012+lpgeiger@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ol-cli = { path = "../../ol-cli"}
futures = "0.3.6"
tokio = { version = "0.2.22", features = ["full"] }
warp = "0.2.5"
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1.0"
cli = { path = "../../testsuite/cli/", version = "0.1.0" }
libra-json-rpc-client = { path = "../../client/json-rpc", version = "0.1.0" }
toml = "0.5.8"