[workspace]
miner_home = "."
node_home = "."

[profile]
account = "D540BE73362A2AB212691F2E0CA141F8"
auth_key = "fbf2cd048859d4455296dc7b07ecdd8ad540be73362a2ab212691f2e0ca141f8"
ip = "1.1.1.1"
statement = "Protests rage across the nation"

[chain_info]
chain_id = "0L testnet"
block_dir = "test_fixtures_miner_3"
