[package]
name = "event-notifications"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
repository = "https://github.com/diem/diem"
description = "The notification service offered by state sync for on-chain events"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
async-trait = "0.1.42"
futures = "0.3.12"
itertools = { version = "0.10.0", default-features = false }
serde = { version = "1.0.124", default-features = false }
thiserror = "1.0.24"
tokio = { version = "1.8.1" }

channel = { path = "../../../crates/channel" }
diem-id-generator = { path = "../../../crates/diem-id-generator" }
diem-infallible = { path = "../../../crates/diem-infallible" }
diem-types = { path = "../../../types" }
diem-workspace-hack = { version = "0.1", path = "../../../crates/diem-workspace-hack" }
storage-interface = { path = "../../../storage/storage-interface" }


[dev-dependencies]
bcs = "0.1.2"
claims = "0.7.1"

diem-crypto = { path = "../../../crates/diem-crypto" }
diem-temppath = { path = "../../../crates/diem-temppath" }
diem-vm = { path = "../../../diem-move/diem-vm" }
diemdb = { path = "../../../storage/diemdb" }
executor-test-helpers = { path = "../../../execution/executor-test-helpers" }
move-core-types = { git = "https://github.com/0LNetworkCommunity/move-0L", rev = "8f3c187e26a519e7c974634c0ad14c5e80f57a33" }
vm-genesis = { path = "../../../diem-move/vm-genesis", features = ["fuzzing"] }
