[package]
name = "ol-util"
# authors = ["Graydon Hoare", "Fnu Lnu <no-reply@rust-lang.org>"]
version = "0.1.0"
edition = "2018"

[dependencies]
ol-global-constants = { path = "../config/global-constants" }
dirs = "2.0.2"
regex = "1"
chrono = "0.4"
fs_extra = "1"