[package]
name = "offchain"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem offchain sdk module"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
base64 = "0.21.0"
bech32 = "0.9.1"
hex = "0.4.3"
rand = "0.8.3"
rand_core = "0.6"
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.61"
serde_repr = "0.1"
thiserror = "1.0.24"
url = "2.2.2"
uuid = { version = "1.3.0", features = ["serde"] }

diem-sdk = { path = ".." }

[dev-dependencies]
rand_core = "0.6"
rstest = "0.15.0"

diem-workspace-hack = { path = "../../common/workspace-hack" }
