[workspace]
node_home = "."

[profile]
account = "16259DC26848A57B940E15FAB6E167CC"
auth_key = "6911626bd4bc2ee051bfbe3ef8369b9316259dc26848a57b940e15fab6e167cc"
ip = "1.1.1.1"
statement = "Protests rage across the nation"

[chain_info]
chain_id = "0L testnet"
block_dir = "test_fixtures_miner_5"
