[workspace]
miner_home = "."
node_home = "."

[profile]
account = "E63FDF1EC186EA85333F95DFD383B28D"
auth_key = "09debbc7886d568a56fe8b85cf346023e63fdf1ec186ea85333f95dfd383b28d"
ip = "1.1.1.1"
statement = "Protests rage across the nation"

[chain_info]
chain_id = "0L testnet"
block_dir = "test_fixtures_miner_5"
